  export default {
      AMAZON_LOGO : require('../assets/amazon.png'),
      UAE_FLAG : require('../assets/uae.png'),
      CAROUSAL_1 : require('../assets/body.jpg'),
      CAROUSAL_2 : require('../assets/c2.jpg'),
      CAROUSAL_3 : require('../assets/c3.jpg'),
      CAROUSAL_4 : require('../assets/c4.jpg'),
      CAROUSAL_5 : require('../assets/c5.jpg'),
      CAROUSAL_6 : require('../assets/c6.jpg'),
      CAROUSAL_7 : require('../assets/c7.jpg'),

      AIRFRYERS : require('../assets/offers/airfryers.jpg'),
      APPLIANCE_STORE : require('../assets/offers/appliancestore.jpg'),
      COFFIE_MACHINES : require('../assets/offers/coffie machines.jpg'),
      VACCUM_CLEANER : require('../assets/offers/vaccum cleaner.jpg'),

      XIOMI : require('../assets/offers/xiomi.jpg'),

      GROOMING : require('../assets/offers/grooming.jpg'),
      BEAUTY : require('../assets/offers/Beauty.jpg'),
      NUTRITION : require('../assets/offers/nutrition.jpg'),
      PERSONAL : require('../assets/offers/personal.jpg'),
      
      SHOPENOW : require('../assets/offers/shopenow.jpg'),

      BEAUTY2 : require('../assets/offers/b1.jpg'),
      PERSONAL2 : require('../assets/offers/p4.jpg'),
      GROCERY : require('../assets/offers/g3.jpg'),
      HOMECARE : require('../assets/offers/h2.jpg'),

      APPLIANCE_STORE2 : require('../assets/offers/appliancestore2.jpg'),
      WASHINGMACHINE : require('../assets/offers/washingmachine.jpg'),
      REFRIGERATOR : require('../assets/offers/refrigerator.jpg'),
      MICROOVEN : require('../assets/offers/microoven.jpg'),

      TOY : require('../assets/offers/toystore.jpg'),
      PUSH : require('../assets/offers/pushpop toys.jpg'),
      SCOOTER : require('../assets/offers/scooter.jpg'),
      ACTIONFIGURE : require('../assets/offers/action figure.jpg'),
      
      CLOTHS : require('../assets/offers/clothing.jpg'),
      SHOES : require('../assets/offers/shoes.jpg'),
      WATCHES : require('../assets/offers/watches.jpg'),
      WALLETS : require('../assets/offers/bags.jpg'),

    //todays offers

    ITEM1 : require('../assets/todaySpecials/item1.jpg'),
    ITEM2 : require('../assets/todaySpecials/item2.jpg'),
    ITEM3 : require('../assets/todaySpecials/item3.jpg'),
    ITEM4 : require('../assets/todaySpecials/item4.jpg'),
    ITEM5 : require('../assets/todaySpecials/item5.jpg'),
    ITEM6 : require('../assets/todaySpecials/item6.jpg'),
    ITEM7 : require('../assets/todaySpecials/item7.jpg'),
    ITEM8 : require('../assets/todaySpecials/item8.jpg'),
    ITEM9 : require('../assets/todaySpecials/item9.jpg'),
    ITEM10 : require('../assets/todaySpecials/item10.jpg'),
    ITEM11 : require('../assets/todaySpecials/item11.jpg'),
    ITEM12 : require('../assets/todaySpecials/item12.jpg'),
    ITEM13 : require('../assets/todaySpecials/item13.jpg'),
    ITEM14 : require('../assets/todaySpecials/item14.jpg'),
    ITEM15 : require('../assets/todaySpecials/item15.jpg'),
    ITEM16 : require('../assets/todaySpecials/item16.jpg'),
    ITEM17 : require('../assets/todaySpecials/item17.jpg'),
    ITEM18 : require('../assets/todaySpecials/item8.jpg'),
    ITEM19 : require('../assets/todaySpecials/item19.jpg'),
    ITEM20 : require('../assets/todaySpecials/item20.jpg'),
    ITEM21 : require('../assets/todaySpecials/item5.jpg'),
    ITEM22 : require('../assets/todaySpecials/item2.jpg'),

    //health and beauty

    ITEM1110 : require('../assets/Health/item1.jpg'),
    ITEM211 : require('../assets/Health/item2.jpg'),
    ITEM31 : require('../assets/Health/item3.jpg'),
    ITEM41 : require('../assets/Health/item4.jpg'),
    ITEM51 : require('../assets/Health/item5.jpg'),
    ITEM61 : require('../assets/Health/item6.jpg'),
    ITEM71 : require('../assets/Health/item7.jpg'),
    ITEM81 : require('../assets/Health/item8.jpg'),
    ITEM91 : require('../assets/Health/item9.jpg'),
    ITEM101 : require('../assets/Health/item10.jpg'),
    ITEM111 : require('../assets/Health/item11.jpg'),
    ITEM1210 : require('../assets/Health/item12.jpg'),
    ITEM131 : require('../assets/Health/item13.jpg'),
    ITEM141 : require('../assets/Health/item14.jpg'),
    ITEM151 : require('../assets/Health/item15.jpg'),
    ITEM161 : require('../assets/Health/item16.jpg'),
    ITEM171 : require('../assets/Health/item17.jpg'),
    ITEM181 : require('../assets/Health/item8.jpg'),
    ITEM191 : require('../assets/Health/item19.jpg'),
    ITEM201 : require('../assets/Health/item20.jpg'),
    ITEM2111 : require('../assets/Health/item5.jpg'),
    ITEM221 : require('../assets/Health/item2.jpg'),

  }